[CRDOM203][5R] add DocType rule as ecorule
green-code-initiative/creedengo-common pull request #16
Opened 2023-04-07 18:24 UTC by Silicoman

As discuss here, https://github.com/green-code-initiative/ecoCode/issues/103

Add new rule to label as eco-design

2023-04-10 21:22 UTC, dedece35 requested changes
before merging this PR, waiting for #17, thus I modify this PR to Draft.
Then, add an explanation of adding this rule as "eco-design" type

2023-04-10 21:22 UTC, dedece35 commented on tools/rules_config/_config.sh
> +RULES_KEYS=css:S4655,php:S2014,Web:ItemTagNotWithinContainerTagCheck,Web:DoctypePresenceCheck
please remove other rules because they are only for testing the system

2023-04-11 20:23 UTC, dedece35 submitted a review, later dismissed

2023-04-11 21:40 UTC, Silicoman commented
i Have resolved with the new script. It's ok, logs below.
I have deleted examples from main.

I'm waiting infos from [issue opened if it's a relevant. ](https://github.com/green-code-initiative/ecoCode/issues/103)

```
--- DEBUG --- Read file ./SONAR_RULES_REUSED.md
--- DEBUG --- Extracting rules: Web:DoctypePresenceCheck

--- DEBUG --- SONAR_TOKEN : xxxxxxxxxxxxxxxxxxxxxxxxx
--- DEBUG --- SONAR_URL : http://localhost:9000
--- DEBUG --- RULES_KEYS : Web:DoctypePresenceCheck
--- DEBUG --- TAG_ECOCONCEPTION : test1

*****  Checking SonarQube connection  *****
--- DEBUG --- SonarQube connection ok : 200

*****  Processing rule Web:DoctypePresenceCheck  *****
Existing sysTags : [
  "user-experience"
]
Existing tags : []
--- DEBUG ---   Processing systag user-experience
  Tag test1 NOT FOUND in tags array nor in systags array : we will add it to rule 'Web:DoctypePresenceCheck'
Execution of command : curl -u xxxxxxxxxxxxxxxxxxxxxxx: -s -o /dev/null --request POST "http://localhost:9000/api/rules/update?key=Web:DoctypePresenceCheck&tags=test1"
CALL to Sonar API to add tag

==> 1 rules updated
```

2023-04-13 21:30 UTC, dedece35 commented
Hi @Silicoman,
ok for me, now.
did you think about our documentation on how to upgrade our installation doc (for developers and clients) ?

2023-05-16 19:57 UTC, dedece35 commented
Hi @Silicoman,
after checking, I don't find rule `Web:DoctypePresenceCheck` in SonarQube :(
thus, modification isn't possible.

Do you have this rule when you install SonarQube 10, locally ?

2024-11-18 13:34 UTC, dedece35 commented
Hi @Silicoman and @utarwyn 
any news for this rule ?
do you know this rule id ?
if not, I will refuse this PR.

2024-11-19 00:14 UTC, utarwyn commented
Hello @dedece35,
based on our discussion in https://github.com/green-code-initiative/ecoCode/issues/103, this rule doesn't seem to be eco-design as it stands. So I propose to also close this PR because the `eco-design` tag should not be added to the SonarQube rule.

2024-11-19 12:22 UTC, dedece35 commented
Hi @Silicoman @utarwyn 
like discussed in previous PR, I close this PR without merging it.

2024-11-19 12:22 UTC, closed without merging