rename ecocode to creedengo
green-code-initiative/creedengo-common pull request #55
Opened 2024-11-19 14:14 UTC by Lmgrto

2024-12-31 11:13 UTC, dedece35 requested changes
please check conflicts before I review (I made some work on this repo, sorry)

2025-01-03 10:26 UTC, Lmgrto commented
No more conflicts

2025-01-03 22:48 UTC, dedece35 requested changes

2025-01-03 22:48 UTC, dedece35 commented on doc/CODE_OF_CONDUCT.md
> +- [Code of Conduct - Creedengo](#code-of-conduct---creedengo)
sorry ... but the title is considered in table ... maybe change the style of title to only have real documentation section and not the title in table of contents

2025-01-03 22:48 UTC, dedece35 commented on doc/CODE_STYLE.md
> +- [Code Style Guide - Creedengo](#code-style-guide---creedengo)
sorry ... but the title is considered in table ... maybe change the style of title to only have real documentation section and not the title in table of contents

2025-01-03 22:48 UTC, dedece35 commented on doc/HOWTO.md
> +This is the use case for `creedengo` repository
false : it's "creedengo-rules-specifications" repo

2025-01-03 22:48 UTC, dedece35 commented on doc/CONTRIBUTING.md
> +- if it isn't exist, create a new issue in `creedengo` repository : choose `new rule template`
false : it's "creedengo-rules-specifications" repo

2025-01-03 22:48 UTC, dedece35 commented on doc/HOWTO.md
> +- go to "Action" tab of `creedengo` repository
false : it's "creedengo-rules-specifications" repo

2025-01-03 22:48 UTC, dedece35 commented on doc/HOWTO.md
> +These GPG keys are stored in Github Secrets available `Settings` tab of `creedengo` repository, in `Secrets and variables` sub-tab, in `Actions` sub-section.
false : it's "creedengo-rules-specifications" repo

2025-01-03 22:48 UTC, dedece35 commented on doc/starter-pack.md
> +- 3rd step - check that local environment is running perfectly : choose one of repositories with suffix "test-project" (ex : <https://github.com/green-code-initiative/creedengo-java-test-project/tree
please use another repo because this one doesn't exist yet ... use "creedengo-python-test-project" and check that this url is OK

2025-05-13 20:21 UTC, closed without merging